// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestaurantApi.Domain.Entities
{
    public partial class RangoReserva
    {
        public RangoReserva()
        {
            Reservas = new HashSet<Reserva>();
        }

        public int IdRangoReserva { get; set; }
        public string Descripcion { get; set; }
        public int Cupo { get; set; }

        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}