// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi.Repository;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(ReservaRestaurantContext))]
    [Migration("20260304191009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantApi.Domain.Entities.RangoReserva", b =>
                {
                    b.Property<int>("IdRangoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rango_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRangoReserva"));

                    b.Property<int>("Cupo")
                        .HasColumnType("int")
                        .HasColumnName("cupo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdRangoReserva")
                        .HasName("PK__rango_re__E110E7BBC5D238EB");

                    b.ToTable("rango_reserva", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Domain.Entities.Reserva", b =>
                {
                    b.Property<string>("CodReserva")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cod_reserva");

                    b.Property<string>("ApellidoPersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_persona");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_personas");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_reserva");

                    b.Property<int>("IdRangoReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_rango_reserva");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mail");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_persona");

                    b.HasKey("CodReserva")
                        .HasName("PK__reserva__12EE26860D1B7BCA");

                    b.HasIndex("IdRangoReserva");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("RestaurantApi.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("RestaurantApi.Domain.Entities.RangoReserva", "IdRangoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdRangoReserva")
                        .IsRequired()
                        .HasConstraintName("FK__reserva__id_rang__398D8EEE");

                    b.Navigation("IdRangoReservaNavigation");
                });

            modelBuilder.Entity("RestaurantApi.Domain.Entities.RangoReserva", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
